image: bjodah/trusty-drone-miniconda27  # contains git, wget, gcc, g++, gfortran, cmake, valgrind, miniconda
git:
    path: github.com/bjodah/pybestprac
env:
  - BINSTAR_USER=bjodah
  - PYTHON_VERSION=2.7
  - CONDA_PY=27
  - ENV_NAME=pybestprac_testenv
script:
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda update --quiet --all
  - conda config --add channels http://conda.binstar.org/$BINSTAR_USER
  - source ./scripts/setup_conda_testenv.sh $PYTHON_VERSION $ENV_NAME
  - conda info
  - python --version
  - python setup.py --version
  - export DISTUTILS_DEBUG=1
  - conda build conda-recipe
  - conda install --quiet pybestprac --use-local
  - TEST_INSTALL=1 bash -x -e ./scripts/run_tests.sh
