image: bjodah/trusty-drone-miniconda27  # contains git, wget, gcc, g++, gfortran, cmake, valgrind, miniconda
git:
    path: github.com/bjodah/pybestprac
env:
  - BINSTAR_USER=bjodah
script:
  - export PATH=$MINICONDA_PATH/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels http://conda.binstar.org/$BINSTAR_USER
  - conda update --quiet --all
  - /bin/bash -x ./scripts/ci_drone.sh 2.7 27 pybestprac_testenv27
  - /bin/bash -x ./scripts/ci_drone.sh 3.4 34 pybestprac_testenv34
